### ISSUE TITLE
Structures auto deleting after pasting in dscan

### ISSUE THREAD

**Issue by usshauler** [goryn-clade/pathfinder-containers#28]
As per usual, I have been adding in structures as normal by d-scanning and pasting into structures list. I have noticed that after pasting even 2 or more, at least one of the structures is removing itself on initial paste. I would have to re-paste the dscan for the structure to remain in the list.

**Comment by samoneilll** [comment]
Duplicate of https://github.com/goryn-clade/pathfinder/issues/20, we already have a fix that will be included in next release of goryn-clade/pathfinder
