### ISSUE TITLE
presetup issue

### ISSUE THREAD

**Issue by cpjet64** [goryn-clade/pathfinder-containers#34]
Just standing up a brand new VM for this because the website I've been using constantly stops tracking position.
Ubuntu Server 20.04.3
10 vCPU
16GB vRAM

location of .env is /home/pathfinder/pathfinder-containers/.env

Googled the error as I don't use docker very much and came up with a issue about relative links but since I have the absolute path entered in the env file figured I should just ask.

If need be I can just wipe and rebuild the VM.

`root@pathfinder:/home/pathfinder/pathfinder-containers# docker network create web && docker-compose up -d --build
d86bfa6ad3d9bf8c2a6d52effaacc909e5ec5d6b62e8b9b5732165ecfb6f0ebb
ERROR: Named volume ""/home/pathfinder/pathfinder-containers"       # The path of the cloned repo/pathfinder/export/sql/eve_universe.sql.zip:/eve_universe.sql.zip:rw" is used in service "pfdb" but no declaration was found in the volumes section.`

```
PROJECT_ROOT="/home/pathfinder/pathfinder-containers"       # The path of the cloned repo 

CONTAINER_NAME="pf"   # docker container name prefix

DOMAIN="https://url/sso/callbackAuthorization"             # The domain you will be using

APP_PASSWORD="pass"       # Password for /setup

MYSQL_PASSWORD="pass"     # Mysql Password

CCP_SSO_CLIENT_ID="token"  # Use the SSO tokens created in step 1

CCP_SSO_SECRET_KEY="token" 

CCP_ESI_SCOPES="esi-location.read_online.v1,esi-location.read_location.v1,esi-location.read_ship_type.v1,esi-ui.write_waypoint.v1,esi-ui.open_window.v1,esi-universe.read_structures.v1,esi-corporations.read_corporation_membership.v1,esi-clones.read_clones.v1,esi-characters.read_corporation_roles.v1"
```

**Comment by fleischsalatinspace** [comment]
> Just standing up a brand new VM for this because the website I've been using constantly stops tracking position. 
This is not related to the Pathfinder instance as CCP ESI API is very unstable/broken since 2021-01-05 19:00 UTC

Regarding your issue: can you post line 1 with `PROJECT_ROOT` of your `.env` file ?

**Comment by fleischsalatinspace** [comment]
Never mind , missed the line because of the formatting. Can you post the exact command you have run and the output?

**Comment by cpjet64** [comment]
i will put down exactly how i did it

git clone --recurse-submodules  https://github.com/goryn-clade/pathfinder-containers.git

modify .env saved to /home/pathfinder/pathfinder-containers/.env

docker network create web && docker-compose up -d --build

the last line of commands listed are what throw the error

**Comment by cpjet64** [comment]
im trying to get this running before i push it into a full lemp stack end goal being a ready to deploy ubuntu setup from start to finish

**Comment by fleischsalatinspace** [comment]
the DOMAIN variable from your .env doesn't look right.
DOMAIN only includes the domain itself, not the URL. So use something like DOMAIN="pathfinder.MYCOOLDOMAIN.com"

**Comment by ArchEcho** [comment]
In your .env file you need to remove the quotation marks on PROJECT_ROOT.

**Comment by fleischsalatinspace** [comment]
@cpjet64 any progress here?

**Comment by cpjet64** [comment]
Sorry for the late response on this I have had a IRL emergency occur and have sidelined everything until its resolved! Nothing life or death thankfully but I have no free time as of now to do anything really. I will bookmark this issue and try the suggestion above when I am able to again. Please feel free to close this issue.

**Comment by fleischsalatinspace** [comment]
No problem. Just reopen it if you have time for it. Stay safe IRL o7
