### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by Soupofdoom** [goryn-clade/pathfinder-containers#37]
when attempting to reach the pathfinder instance after following the setup, i end up at a 404, even from an internal IP address. I have an error from the traefik container (below). If i go to the internal ip port:8080 i can access the traefik dashboard.

error: `traefik      | time="2022-01-17T19:16:33Z" level=error msg="Unable to obtain ACME certificate for domains \"pathfinder.mycooldomain.com\": unable to generate a certificate for the domains [pathfinder._mycooldomain_.com]: error: one or more domains had a problem:\n[pathfinder.mycooldomain.com] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://pathfinder.mycooldomain.com/.well-known/acme-challenge/FkG9ARW-6snCRpZagnCpeYe70JaBmlvzPApRfnF9KgQ [77.100.152.248]: \"<html>\\r\\n<head><title>404 Not Found</title></head>\\r\\n<body>\\r\\n<center><h1>404 Not Found</h1></center>\\r\\n<hr><center>openresty</cente\", url: \n" rule="Host(`pathfinder.mycooldomain.com`)" providerName=letsencrypt.acme routerName=pf-secure@docker
`

.env:
`PROJECT_ROOT="/root/pathfinder-containers"
CONTAINER_NAME="pf"
DOMAIN="pathfinder.mycooldomain.com"
APP_PASSWORD="thepassword"
MYSQL_PASSWORD="theotherpassword"
CCP_SSO_CLIENT_ID="yup this is correct"
CCP_SSO_SECRET_KEY="also correct"
CCP_ESI_SCOPES="esi-location.read_online.v1,esi-location.read_location.v1, etc etc... (cant copy this for some reason)`

`

**Comment by fleischsalatinspace** [comment]
sorry i missed this. I suspect you don't actually own `mycooldomain.com`, so you need to provide a valid domain in the `.env` file. Also if you have modified the domain, make sure you have a valid DNS A-record for this domain pointing to your external ip address.  
If you need any help configuring this, feel free to hop onto [Pathfinder slack](https://join.slack.com/t/pathfinder-eve-online/shared_invite/enQtMzMyOTkyMjczMTA3LWI2NGE1OTY5ODBmNDZlMDY3MDIzYjk5ZTljM2JjZjIwNDRkNzMyMTEwMDUzOGQwM2E3ZjE1NGEwNThlMzYzY2Y)  

I'll close this for now as it looks like a misconfiguration, you can reopen the issue any time.

**Comment by fleischsalatinspace** [comment]
FTR: we chatted on slack and the OP used nginx proxy manager as central reverse proxy.
