### ISSUE TITLE
[DOC] Documentation Input

### ISSUE THREAD

**Issue by ScotDex** [goryn-clade/pathfinder-containers#42]
Hey Guys.

Just need to gather some ideas before I start, I spoke with goryn-clade and got permission to contribute to writing the wiki for the main fork https://github.com/goryn-clade/pathfinder - I am keen to do the same here but part of his suggestion was to add documentation related to know/regular issues occurring and the solutions. Would you guys be kind enough to add to this thread with that information?

I am also going to assemble a bit of documentation on how to separate the pathfinder and traefik and allow it to run separate so you can take the pathfinder offline for maintenance to avoid it impacting existing deployments (as goryn mentioned)

Cheers

**Comment by fleischsalatinspace** [comment]
Thank you for your work. I have just added a rudimentary guide on upgrading to v.2.2.x https://github.com/goryn-clade/pathfinder-containers/wiki/v2.2.*--to--v2.2.1-Upgrade-Guide
