### ISSUE TITLE
[IMPROVEMENT] Publish PF Docker Container Instead of Letting Docker-Compose Build It

### ISSUE THREAD

**Issue by ZaxLofful** [goryn-clade/pathfinder-containers#44]
I am requesting that you build and store the docker containers ahead of time.

Both the normal Docker repo and GitHub's Docker repo are free of charge and will host these for you; GitHub will even build them for you I believe.

I come from a DevOps engineer background and its best practice not to have your docker-compose file do any building or compiling; just find the images needed and deploy them.

I would love to use this repo image, but I don't want to download your repo every-time. I just want a docker-compose file that points to your compiled version (either on GitHub or Docker).

This also adds modularization correctly. What you have is great for a personal project, but lacks the modularization for scale. It feels like a dev build.

**Comment by greg2010** [comment]
I've needed this to use a different orchestrator than docker-compose so I've set up github actions for image building here (along with additional environment variables to make config not compose-specific): https://github.com/greg2010/pathfinder-containers
@samoneilll let me know if that is something you want upstream and I'll send an MR.

**Comment by ZaxLofful** [comment]
You should create a PR request for it, I would very much like this feature as well!

**Comment by samoneilll** [comment]
Hey Team, 

I'm happy to publish a docker image, if you want to make a PR @greg2010 I'd be interested to see how it's done and merge it.

**Comment by ZaxLofful** [comment]
I have recently found that you can do this automatically with GitHub Actions, you might want to give it a try for your repo:

https://github.com/marketplace/actions/build-and-push-docker-images

**Comment by samoneilll** [comment]
Hi All, this has now been mreged. I'll create a release shortly to trigger the Action pipeline
