### ISSUE TITLE
Can't update structure owning entity

### ISSUE THREAD

**Issue by ecortinas** [goryn-clade/pathfinder-containers#51]
When I try to add an owning entity for a structure I get a 403 error.
![error](https://user-images.githubusercontent.com/88294949/221955867-9d1899e8-7335-4d76-bf00-9dd271a04f87.png)

**Comment by samoneilll** [comment]
Hi @ecortinas we needed to add the `esi-search.search_structures.v1` in a recent release. To get this working you'll need to add this scope to the list of scopes in the .env file, and also enable the scope in the app setup at developers.eve-online.com.
