### ISSUE TITLE
The PF Container gets "invalid number of arguments" in site.conf and doesnt run container

### ISSUE THREAD

**Issue by fallenreaper** [goryn-clade/pathfinder-containers#61]
I set up the ENV, instead of base docker, I use colima, another container utility. Works wonders.
i run `docker network create web && docker-compose up -d --build`

I did a quick follow to see if i was missing anything.  `docker compose logs --follow`.  When I was looking at a localhost implementation, I was thinking that I could then go to localhost/setup but get a 404.

When looking at the logs I notice:
> pathfinder-containers-pf-1         | 2023/06/30 05:12:25 [emerg] 15#15: invalid number of arguments in "server_name" directive in /etc/nginx/sites_enabled/site.conf:5
> pathfinder-containers-pf-1         | nginx: [emerg] invalid number of arguments in "server_name" directive in /etc/nginx/sites_enabled/site.conf:5
> pathfinder-containers-pf-1         | 2023-06-30 05:12:25,359 INFO exited: nginx (exit status 1; not expected)

It looks like it seems to have never properly deploys in that container and errors out, which makes sense as to why there is a 404.

The ENV file I used was based on `.env.example` instead of the Readme.  I only edited le_email, mysql password, app password, and eve sso.

I made no changes to the config ini.

**Comment by nefyodovve** [comment]
@fallenreaper 

You should edit `DOMAIN=""` in `.env` file.

**Comment by TyrHeimdalEVE** [comment]
@nefyodovve is right, the `DOMAIN` variable is what generates `server_name` in this file, so verify the `.env` file according to the documentation.
