### ISSUE TITLE
SSL Certificate Issue

### ISSUE THREAD

**Issue by TilleyTech** [goryn-clade/pathfinder-containers#69]
All setup and working perfect except the browser says its not secure. If i inspect the certificate it has the correct domain and i deleted the  acme.json file let it re-create and inspecting that it also now has the correct domain in. Firefox gives this error Error code: SEC_ERROR_UNKNOWN_ISSUER

Of course i can add an exception and continue but trying to clean it all up for the user experience.

**Comment by nefyodovve** [comment]
Did you do the following steps from README?

![image](https://github.com/goryn-clade/pathfinder-containers/assets/25212107/313b88a6-0a31-416c-9ddb-12c47fa10887)

But in fact it is not line 89, but line 84 in `docker-compose.yml`:

![image](https://github.com/goryn-clade/pathfinder-containers/assets/25212107/64915209-bbba-4f72-b04a-697f48119308)

**Comment by TilleyTech** [comment]
Thankyou, that sorted it, yes initially i deleted the acme.json and the line it specified. I stopped the container, re-deleted acme.json deleted line 84 brought up the container and boom all sweet. Thanks man :)

**Comment by nefyodovve** [comment]
@TilleyTech don't forget to restore previous deleted line
You're welcome :)
