### ISSUE TITLE
DB setup issues

### ISSUE THREAD

**Issue by anesbit** [goryn-clade/pathfinder-containers#74]
![image](https://github.com/goryn-clade/pathfinder-containers/assets/2560564/cdd46f08-f815-4c57-9d47-2716878b3b4d)
 I have been working on this for hours now and this has been an issue on multiple peice of hardware... I cant get the "DB Driver" to be recognized and every time I try to use an external DB it cant find the host... I know that the container includes a DB... this is starting to piss me off cause IDK what else to do to get it working. Any help would be amazing.

Thanks!

**Comment by Pymous** [comment]
Hey there !

Can't be sure, as I'm not one of the contributor/maintainer, but could you share a little bit more details about your installation ? 

By my experience, `No such file or directory` at this level would mean that it can't get access to the port/socket of your MySQL/MariaDB.

Are you using the DB provided with the containers ?
- If Yes, did you alter the config in any way ?
- If No, where is your DB ?

Good luck !

**Comment by anesbit** [comment]
So I have tried it in multiple setups.. I have tried with the built-in DB and external DB. 

With the internal DB, I have literally only changed the DOMAIN = Config value to match the domain.... everything else was left alone.
![image](https://github.com/goryn-clade/pathfinder-containers/assets/2560564/740287cd-e95a-41c9-b35c-f3f48e25a8fb)
This produces a 403 Forbidden and the /setup route... it is not disabled in the routes.ini file.

On the External DB, I keep getting a connection refused when trying to connect with an external DB but the setup route works and loads the UI. I tried checking the logs for the docker container but had no luck finding any errors to try and trace to get anything running.

**Comment by anesbit** [comment]
UPDATE:
So after restarting the container.... I got the UI to load on the default config file once before returning 403's... This is what it said...
![image](https://github.com/goryn-clade/pathfinder-containers/assets/2560564/5bd7b986-bb99-403e-a82d-760c4bb6803f)

**Comment by anesbit** [comment]
FIXED IT....

So for future refrence, I had to manually set the Root DB Password in the docker-compose.yml and make the password match in the config file.

**Comment by TyrHeimdalEVE** [comment]
This sounds like an issue with Docker version and quotation in the `.env` file. This can be quite tricky in some cases.

At first though, it was failing due to you changing the host for the DB. At that point, based on the first pictures - the password was fine. Only after were there issues with the password. Thus, somewhere along the line, you broke it.
