### ISSUE TITLE
Issues trying to run on ARM

### ISSUE THREAD

**Issue by tmckzs** [goryn-clade/pathfinder-containers#75]
Docker is giving `exec format error` in the logs of pathfinder-containers_pf-socket_1 and pathfinder-containers_pfdb_1. Trying to set up a host on an Orange Pi 5 running Armbian Ubuntu. Guessing it's an architecture mismatch?

(I'm a noob, sorry).

**Comment by TyrHeimdalEVE** [comment]
Unfortunately we rely on containers which are x86 based, and these will probably not be built to handle ARM architecture in the forseeable future.

What you could do is spin up an x86 compatible VM and run docker inside there instead.
