### ISSUE TITLE
Stuck with manager role, can't delete test maps

### ISSUE THREAD

**Issue by rykugur** [goryn-clade/pathfinder-containers#76]
Hi there. I followed the docker-compose guide, and got everything up and running pretty easily. I then disabled the bundled traefik and set up my own traefik container. That's all working great.

However, my character that I'm logged in as is seemingly stuck on manager. I have a couple maps I created to test/learn with and would like to delete them, but it tells me that I need the admin role to do that. When I go to `pathfinder.url.com/admin` it shows me:

![image](https://github.com/goryn-clade/pathfinder-containers/assets/2609898/77cde472-9c5e-45b6-bab7-b81daeb119a4)

My in-game role shows I have director (I think?) - has the backslash through the box.

Am I doing something wrong?

EDIT:

I have verified the permissions on EVE developers.

**Comment by weinerberry1974** [comment]
Try making the map private then try deleting it.

**Comment by rykugur** [comment]
> Try making the map private then try deleting it.

Well... hindsight says "that seems simple."

That worked, and I guess is a sufficient work-around, thank you.
