### ISSUE TITLE
Getting unknown database error when setting up.

### ISSUE THREAD

**Issue by Thor6677** [goryn-clade/pathfinder-containers#77]
Getting the error below in the patherfinder-containers-pf-1 when first setting this up.

This is attempting to setup in a Amazon EC2 

Sun, 31 Dec 2023 16:53:00 +0000 PDOException: SQLSTATE[HY000] [1049] Unknown database 'pathfinder' in /var/www/html/pathfinder/vendor/bcosca/fatfree-core/db/sql.php:548    
Sun, 31 Dec 2023 16:53:00 +0000 Stack trace:                                                                                                             
Sun, 31 Dec 2023 16:53:00 +0000 #0 /var/www/html/pathfinder/vendor/bcosca/fatfree-core/db/sql.php(548): PDO->__construct('mysql:host=mari...', 'root', '104414', Array)
Sun, 31 Dec 2023 16:53:00 +0000 #1 /var/www/html/pathfinder/app/Lib/Db/Sql.php(19): DB\SQL->__construct('mysql:host=mari...', 'root', 104414, Array)                 
Sun, 31 Dec 2023 16:53:00 +0000 #2 /var/www/html/pathfinder/app/Lib/Db/Pool.php(185): Exodus4D\Pathfinder\Lib\Db\Sql->__construct('mysql:host=mari...', 'root', 104414, Array)
Sun, 31 Dec 2023 16:53:00 +0000 #3 /var/www/html/pathfinder/app/Lib/Db/Pool.php(142): Exodus4D\Pathfinder\Lib\Db\Pool->newDB(Array)            
Sun, 31 Dec 2023 16:53:00 +0000 #4 /var/www/html/pathfinder/app/Model/AbstractModel.php(152): Exodus4D\Pathfinder\Lib\Db\Pool->getDB('PF')
Sun, 31 Dec 2023 16:53:00 +0000 #5 /var/www/html/pathfinder/app/Model/AbstractModel.php(1118): Exodus4D\Pathfinder\Model\AbstractModel->__construct(NULL, NULL, NULL, 86400)
Sun, 31 Dec 2023 16:53:00 +0000 #6 /var/www/html/pathfinder/app/Lib/Cron.php(133): Exodus4D\Pathfinder\Model\AbstractModel::getNew('Exodus4D\\Pathfi...')
Sun, 31 Dec 2023 16:53:00 +0000 #7 /var/www/html/pathfinder/app/Lib/Cron.php(38): Exodus4D\Pathfinder\Lib\Cron->getJob('deleteLogData')                                 
Sun, 31 Dec 2023 16:53:00 +0000 #8 /var/www/html/pathfinder/vendor/xfra35/f3-cron/lib/cron.php(148): Exodus4D\Pathfinder\Lib\Cron->isDue('deleteLogData', 1704041580)
Sun, 31 Dec 2023 16:53:00 +0000 #9 /var/www/html/pathfinder/vendor/xfra35/f3-cron/lib/cron.php(163): Cron->run()                                                       
Sun, 31 Dec 2023 16:53:00 +0000 #10 /var/www/html/pathfinder/vendor/bcosca/fatfree-core/base.php(1960): Cron->route(Object(Base), Array, Array)     
Sun, 31 Dec 2023 16:53:00 +0000 #11 /var/www/html/pathfinder/vendor/bcosca/fatfree-core/base.php(1759): Base->call(Array, Array, Array)                                       
Sun, 31 Dec 2023 16:53:00 +0000 #12 /var/www/html/pathfinder/index.php(27): Base->run()                                            
Sun, 31 Dec 2023 16:53:00 +0000 #13 {main}

.env file looks like this: (personal info censored)

DOMAIN="##########"
LE_EMAIL="###############"
APP_PASSWORD="14410As"
MYSQL_HOST="mariadb"
MYSQL_PORT="3306"
MYSQL_USER="root"
MYSQL_PASSWORD="104414"
MYSQL_PF_DB_NAME="pathfinder"
MYSQL_UNIVERSE_DB_NAME="eve_universe"
MYSQL_CCP_DB_NAME="eve_lifeblood_min"
REDIS_HOST="redis"
REDIS_PORT="6379"
CCP_SSO_CLIENT_ID="#################"
CCP_SSO_SECRET_KEY="#####################"
CCP_ESI_SCOPES="esi-location.read_online.v1,esi-location.read_location.v1,esi-location.read_ship_type.v1,esi-ui.write_waypoint.v1,esi-ui.open_window.v1,esi-universe.read_structures.v1,esi-corporations.read_corporation_membership.v1,esi-clones.read_clones.v1,esi-characters.read_corporation_roles.v1,esi-search.search_structures.v1"
PATHFINDER_SOCKET_HOST="pathfinder-socket"
PATHFINDER_SOCKET_PORT="5555"
SMTP_HOST=""
SMTP_PORT=""
SMTP_SCHEME=""
SMTP_USER=""
SMTP_PASS=""
SMTP_FROM=""
SMTP_ERROR=""

**Comment by weinerberry1974** [comment]
Are you trying to install the dockerised version ?

**Comment by Thor6677** [comment]
> Are you trying to install the dockerised version ?
Yes.

**Comment by weinerberry1974** [comment]
where is  
PROJECT_ROOT=""
CONTAINER_NAME=""
in your env ?

**Comment by Thor6677** [comment]
So the .env pasted above is a direct copy of the .env.example from the repository. The one in the readme on the main reposityory page looks to be deprecated. 

Even so I have tried that one as well and get the same error.

**Comment by Thor6677** [comment]
So this looks to be some quirk with AWS ECS instances. I even tried a Ubuntu install vs their amazon Linux version as was still getting the same error. I then changed over to use digital ocean droplet with Ubuntu and everything is working as expected.

**Comment by TyrHeimdalEVE** [comment]
Closing this then. If you for some reason have to run it on AWS again, we can take a closer look at it.
