### ISSUE TITLE
Randomly getting error 500

### ISSUE THREAD

**Issue by rykugur** [goryn-clade/pathfinder-containers#78]
I've had a PF instance up and running in a docker container for a few weeks now. I used it just last night and all was well.

Today when I went to open the app, I started getting error 500's:

```
Error - 500

Oooops, Something went wrong! You have experienced a technical error. We apologize.

Status: 'Internal Server Error'
Message: Unable to open img/v2.2.2/svg/logo_inline.svg 
```

I've verified this file exists and is readable:

```
 ll (find . -iname "*logo_inline*")
Permissions Size User  Date Modified Git Name
.rw-r--r--  2.9k dusty 16 Dec  2023   -- ./pathfinder/img/svg/logo_inline.svg
.rw-r--r--  2.9k dusty 16 Dec  2023   -- ./pathfinder/public/img/v2.2.2/svg/logo_inline.svg
```

Thoughts?

EDIT: I do have watchtower running, so it must have pulled the latest image overnight.

**Comment by rykugur** [comment]
Was able to fix through some trial and error.

**Comment by Thor6677** [comment]
What did you do to resolve the issue? I am getting the same error after the update to the new version.

**Comment by rykugur** [comment]
> What did you do to resolve the issue? I am getting the same error after the update to the new version.

I'm not positive, but I think it was because I had made changes to `config/pathfinder/pathfinder.ini` on my fork and the version was incorrect. I didn't really take note of what I did and my `history` doesn't reveal much beyond chaos. I ended up syncing my fork and re-applying my local changes and IIRC it started working after that.
