### ISSUE TITLE
Missing "esi-search.search_structures.v1" results in Search not working | Search Failed

### ISSUE THREAD

**Issue by Poolie30059785** [goryn-clade/pathfinder-containers#87]
When searching an owner for station. ERROR

![image](https://github.com/goryn-clade/pathfinder-containers/assets/167658677/499210b7-779b-4465-b51b-0726a7ef53b2)

**Comment by fleischsalatinspace** [comment]
As stated in the error message, it looks like the Pathfinder instance you are using is missing the scope request for `esi-search.search_structures.v1`.  Please make sure your Pathfinder instance administrator has configured the correct PERMISSIONS for the "EVE ONLINE Application" at the EVE Online Developer portal as described in the README.md at https://github.com/goryn-clade/pathfinder-containers `1. Create an API-Key`  

Let me know if this solved the issue

**Comment by Poolie30059785** [comment]
This

> As stated in the error message, it looks like the Pathfinder instance you are using is missing the scope request for `esi-search.search_structures.v1`. Please make sure your Pathfinder instance administrator has configured the correct PERMISSIONS for the "EVE ONLINE Application" at the EVE Online Developer portal as described in the README.md at https://github.com/goryn-clade/pathfinder-containers `1. Create an API-Key`
> 
> Let me know if this solved the issue

This was resolved, I already had the scope that was showing in the error, it only worked when I requested this scope...
![image](https://github.com/goryn-clade/pathfinder-containers/assets/167658677/c0f6a9ed-2e00-4128-a08f-9f49f1e02856)

**Comment by fleischsalatinspace** [comment]
Thank you for the information. I'll close the issue
