### ISSUE TITLE
Application Error - Error 403

### ISSUE THREAD

**Issue by genevensis** [goryn-clade/pathfinder-containers#96]
I've managed to have PF installed and running, and everything is in the green.
Only modifications I had to do was use "docker compose" and not "docker-compose".
Then after some time, app hands out errors 403 on all connected users.
There is no timing/timer, nothing comes out in the logs (docker compose logs -f -t).

Tried modifying timeout delays in the config files to no success.

Any others with the same issue?

![image](https://github.com/user-attachments/assets/fd5ab246-9388-4a8c-8006-7ffe7f795623)

**Comment by nmlynch94** [comment]
@genevensis since you closed as completed, did you find a solution? I'm facing the same issue on a self-hosted server.

**Comment by genevensis** [comment]
Heya! I’ve upgraded my VPS to 2 gigs of ram and that fixed 95% of those errors. Still catch a few but very manageable. Hope that helps!On 6 Dec 2024, at 10:03, nmlynch94 ***@***.***> wrote:﻿
@genevensis since you closed as completed, did you find a solution? I'm facing the same issue on a self-hosted server.
